apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Values.controller.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      hostNetwork: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        command:
          - ipmanager
          - claimcontroller
          - --iface={{ .Values.controller.interface }}
          - --logtostderr
          - --v=5
          - --hb=500ms
