apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.scheduler.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - ipmanager
        - scheduler
        - --mask={{ .Values.scheduler.network_mask }}
        - --logtostderr
        - --v=5
        - --leader-elect=true
        - --monitor=4s
        - --nodefilter=fair
