sudo: required
language: go
services:
    - docker
before_install:
  - mkdir -p _output/
  - sudo apt-get install -y git
install:
  - make get-deps
script: make test
after_success:
  - ./scripts/push.sh
